### ISSUE TITLE
RPI Camera V1 on RKAIQ 5.0x3.0

### ISSUE THREAD

**Issue by peyton-howe** [OpenHD/rockchip-iq-files#2]
I'm having an issue with the [ov5647_rpi-camera-v1p3_default.json](https://github.com/OpenHD/rockchip-iq-files/blob/main/rockchip-iqfiles-rk356x/ov5647_rpi-camera-v1p3_default.json) tuning file on version 5.0x3.0 of rkaiq.

I made a few modifications to the tuning file in order to get it working with the newer version, which included renaming some of the flags to support the newer version and copying some missing parameters from the ov13855 tuning file. The tuning file now works without throwing any segfaults, but it doesn't appear to be working properly as the image s pixelated and grayscale.
![image](https://github.com/OpenHD/rockchip-iq-files/assets/80078168/b31c0033-9a41-44bc-a054-0b11aa11102e)
My guess is something went wrong when copying parameters from the ov13855 tuning file, but just renaming the flags was not sufficient enough to get the tuning file compatible with 5.0x3.0.

Attached below is my modified tuning file.
[ov5647_rpi-camera-v1_default.json](https://github.com/OpenHD/rockchip-iq-files/files/14790131/ov5647_rpi-camera-v1_default.json)

Also, which version are these tuning files designed for? Thanks!

**Comment by raphaelscholle** [comment]
Try using the official truning files from radxa, tuning files are not made to be easily converted, usually you retune the sensor when anything isn't working correctly
